# Generated by Django 4.2.4 on 2023-08-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0004_cart_category_product_wallet_delete_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/assets/img')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.category')),
            ],
        ),
    ]
