# Generated by Django 4.2.4 on 2023-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0005_index_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='permission',
            field=models.BooleanField(blank=None, default=False, null=None),
        ),
        migrations.DeleteModel(
            name='Index_Product',
        ),
    ]
