# Generated by Django 4.2.5 on 2023-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0007_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
